# Generated by Django 5.2 on 2025-06-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_productdeleteotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdeleteotp',
            old_name='Products',
            new_name='product',
        ),
    ]
