# Generated by Django 5.2 on 2026-07-30 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_productmedia_alt_text_productmedia_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.seller'),
        ),
    ]
