# Generated by Django 5.2 on 2026-07-30 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_articles_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='frontend.seller'),
        ),
        migrations.AlterField(
            model_name='products',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='frontend.seller'),
        ),
    ]
