# Generated by Django 5.2 on 2026-07-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_alter_articles_seller_alter_products_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
