# Generated by Django 5.2 on 2026-08-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_seller_address_seller_city_seller_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='city',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='country',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='state',
        ),
    ]
