# Generated by Django 5.2 on 2026-08-01 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_remove_seller_city_remove_seller_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='seller_banners/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='joined',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seller',
            name='website',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
