# Generated by Django 5.2 on 2026-08-06 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_seller_banner_seller_city_seller_joined_seller_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
