# Generated by Django 5.2 on 2026-08-09 13:54

import frontend.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_alter_category_slug_alter_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=models.FileField(storage=frontend.storage.ProductMediaCloudinaryStorage(), upload_to='uploads/products/'),
        ),
    ]
