# Generated by Django 5.2 on 2026-08-12 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_alter_productmedia_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmedia',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='frontend.category'),
        ),
    ]
