# Generated by Django 5.2 on 2026-08-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_alter_productmedia_options_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
