# Generated by Django 5.2 on 2026-08-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_seller_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
