# Generated by Django 5.2 on 2026-08-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_products_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Leave empty for unlimited / non-fixed stock.', null=True),
        ),
    ]
