# Generated by Django 5.2 on 2026-08-29 10:44

import django.db.models.deletion
import frontend.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_alter_products_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('material_type', models.CharField(choices=[('thread', 'Thread'), ('wool', 'Wool'), ('yarn', 'Yarn'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_code', models.CharField(blank=True, max_length=20)),
                ('hex_code', models.CharField(blank=True, max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=frontend.storage.ProductMediaCloudinaryStorage(), upload_to='uploads/materials/colors/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('material_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='frontend.materialcolor')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(default='unit', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_color', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='frontend.materialcolor')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specification', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='frontend.material')),
            ],
        ),
        migrations.AddField(
            model_name='materialcolor',
            name='material_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='frontend.materialvariant'),
        ),
        migrations.AddConstraint(
            model_name='materialvariant',
            constraint=models.UniqueConstraint(fields=('material', 'name'), name='unique_material_variant'),
        ),
    ]
