# Generated by Django 5.2 on 2026-09-02 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_material_materialcolor_materialcolorimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcolorimage',
            name='image',
            field=models.ImageField(upload_to='uploads/materials/colors/'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=models.FileField(upload_to='uploads/products/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/seller/banners/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/seller/logos/'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Only include contry code and number, no spaces or special characters. Example: 91914053723', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('material_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='frontend.materialcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='frontend.products')),
            ],
        ),
    ]
