# Generated by Django 5.2 on 2026-09-09 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0030_alter_seller_whatsapp_number_inquiry_inquiryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('product_limit', models.PositiveIntegerField(default=10)),
                ('media_limit', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['price', 'product_limit'],
            },
        ),
        migrations.AddField(
            model_name='seller',
            name='payment_mode',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('upi', 'UPI'), ('card', 'Card / Online Payment'), ('bank', 'Bank Transfer'), ('whatsapp', 'WhatsApp Order')], default='cod', max_length=40),
        ),
        migrations.AddField(
            model_name='seller',
            name='plan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sellers', to='frontend.sellerplan'),
        ),
    ]
